CREATE TABLE BLOCKS (
   NUMBER INT,
   HASH CHAR(64),
   NONCE INT NOT NULL,
   PREVIOUSHASH CHAR(64) NOT NULL,
   TIMESTAMP DECIMAL(18, 18) NOT NULL,
   PRIMARY KEY (NUMBER, HASH)
);

CREATE TABLE TRANSACTIONS(
    BLOCKHASH CHAR(64) NOT NULL,
    HASH CHAR(64) NOT NULL,
    RECEIVER CHAR(96) NOT NULL,
    SENDER CHAR(96) NOT NULL,
    AMOUNT DECIMAL (18, 18) NOT NULL,
    TIMESTAMP DECIMAL (18, 18) NOT NULL,
    SIGNATURE CHAR(96),
    NONCE INT NOT NULL,
    FEE DECIMAL (18, 18) NOT NULL,
    PRIMARY KEY (BLOCKHASH, HASH)
);
